### ISSUE TITLE
Previous zabbix version

### ISSUE THREAD

**Issue by alanwds** [itmicus/zabbix#1]
Hi,

It's possible using this template zabbix < 3.4?

Best Regards,
Alan

**Comment by itmicus** [comment]
alanwds, I need time to test on early version.

**Comment by alanwds** [comment]
@skazochnik97 Great. I was in 3.2 and recently upgrade to 3.4. I still get erros on 3.4 template so, i use the legacy and work's like a charm. Thank you!
