### ISSUE TITLE
import issue Template Microsoft Windows Certificates

### ISSUE THREAD

**Issue by baannee** [itmicus/zabbix#15]
zabbix_server (Zabbix) 3.4.7
Revision 77720 16 February 2018, compilation time: Feb 19 2018 07:37:17

Import failed:
`Details
Created: Discovery rule "Local machine certificates discover" on "Template Microsoft Windows Certificates (itmicus.ru)".
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,interfaceid,flags,master_itemid,itemid) VALUES ('Сertificate \"{#LM_CERT_CN} ({#LM_CERT_FRIENDLYNAME})\" run checks','7','','','1d','3d','0','0','4','','','','0','0','','0','','','','0','','','','','','','0','','','windows.certs[get,lm_cert,{#LM_CERT_THUMBPRINT}]','','10228',NULL,'2',NULL,'34313')] [Incorrect string value: '\xD0\xA1erti...' for column 'name' at row 1]
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,interfaceid,flags,master_itemid,itemid) VALUES ('Сertificate \"{#LM_CERT_CN} ({#LM_CERT_FRIENDLYNAME})\" run checks','7','','','1d','3d','0','0','4','','','','0','0','','0','','','','0','','','','','','','0','','','windows.certs[get,lm_cert,{#LM_CERT_THUMBPRINT}]','','10228',NULL,'2',NULL,'34313')".`

**Comment by itmicus** [comment]
let me check

**Comment by itmicus** [comment]
@baannee please download new version  of template. I found issue and fix it
