### ISSUE TITLE
Проблема с запуском скрипта

### ISSUE THREAD

**Issue by Onoro** [itmicus/zabbix#16]
Доброго времени суток.
Zabbix не может получить данные, вручную скрипт не отрабатывает. Прошу помощи.

![hyper1](https://user-images.githubusercontent.com/22278106/43123763-d45a51c4-8f2d-11e8-9d09-b0815a68ab52.jpg)
![hyper2](https://user-images.githubusercontent.com/22278106/43123764-d47cb016-8f2d-11e8-9a72-b733320e8e3f.jpg)

В логах агента и сервера ошибок выполнения скрипта нет.

**Comment by itmicus** [comment]
Привет. 
У Вас один хост или не сколько? не работает везде? 
Можете показать zabbix->host=>открыть хост и перейти в раздел Обнаружения, есть ошибки справа ?

**Comment by Onoro** [comment]
Хост 1.
Ошибок нет.
![default](https://user-images.githubusercontent.com/22278106/43248104-7075c81c-90bf-11e8-811b-8e8fa322c664.png)

**Comment by itmicus** [comment]
Имя хоста в Zabbix консоли, совпадает и именем хоста в конфиге на клиенте?

**Comment by Onoro** [comment]
Да.

**Comment by wmorgue** [comment]
Привет @Onoro 
Ошибка актуальна на данный момент?
