### ISSUE TITLE
Problems with Windows Active Template

### ISSUE THREAD

**Issue by wkriesch** [itmicus/zabbix#17]
hi, I've tried to use Windows Active template, but I have a problem here... Windows 7, 10, working perfectly.... When I install 2008r2, 2012, 2012r2, they didn't bring any information.. 

i've tested ports, scripts, nothing works!!!!

**Comment by itmicus** [comment]
Hello. Please, run PowerShell on a problem Server, then go to directory with os_windows_active.ps1 and execute:
$PSVersionTable
.\os_windows_active.ps1 -ActionType discover -Key ldisk

and give me the output.

**Comment by wkriesch** [comment]
Sorry i Discovered that, the hostname need be the same that configured in zabbix_agentd.conf

**Comment by wkriesch** [comment]
working

**Comment by itmicus** [comment]
Ok, very well ;-)
