### ISSUE TITLE
Website metrics error: 'ascii'

### ISSUE THREAD

**Issue by zhukovd** [itmicus/zabbix#25]
Добрый день! 
При запуске ./website_metrics.py --testsite "http://sitename" --testphrase "2018" --debug "True" выдается ошибка:
Error: 'ascii' codec can't encode characters in position 179-192: ordinal not in range(128)
Сайт работает по http.
Подскажите, в чем может быть проблема?

**Comment by skazochnik97** [comment]
Вроде чинил этот баг в 7def406

**Comment by skazochnik97** [comment]
#3 

До сих пор повторяется?

**Comment by skazochnik97** [comment]
А можете предоставить выхлоп двух команд?

pip --version
pip freeze

Попробую у себя повторить окружение.

**Comment by zhukovd** [comment]
pip 10.0.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

certifi==2018.1.18
chardet==3.0.4
configobj==4.7.2
decorator==3.4.0
idna==2.6
iniparse==0.4
oauthlib==2.1.0
perf==0.1
poster==0.8.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyparsing==1.5.6
PySocks==1.6.8
python-dateutil==2.7.3
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
requests==2.19.1
requests-file==1.4.3
requests-oauthlib==1.0.0
requests-toolbelt==0.8.0
schedutils==0.4
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
tldextract==2.2.0
Unirest==1.1.7
urlgrabber==3.10
urllib3==1.22
yum-metadata-parser==1.1.4

**Comment by zhukovd** [comment]
обновил pip
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
ничего не поменялось

**Comment by skazochnik97** [comment]
Обновил методичку, плюс были патч по телу скрипта.
https://github.com/itmicus/zabbix/blob/master/Template%20Web%20Site/readme.md

Проблема повторяется?
