### ISSUE TITLE
How check cluster iSCSI disks?

### ISSUE THREAD

**Issue by itkroplis** [itmicus/zabbix#27]
Hi!
Or If this hyper-v template is possible check  mounted iSCSI disks in Hyper-V cluster?
I mount in C:\ClusterStorage\Volume1  and Volume2 ....
But I can't find,  how check disk free/total space used for it. 
Or this template that showing it?

**Comment by wmorgue** [comment]
Hi @itkroplis 
You steel need help with this issue?
