### ISSUE TITLE
Discovery trigger error

### ISSUE THREAD

**Issue by eirisdg** [itmicus/zabbix#34]
Hi.

In Logical Disk discover, in the prototypes, there is an error value:
Used Disk "{#LOGICAL_DISK} {#LOGICAL_DISK_VOLUME_NAME}" --> Key is os.windows.active.ldisk.used.mbytes[{#LOGICAL_DISK}] 
and myst be os.windows.active.ldisk.used.bytes[{#LOGICAL_DISK}]

**Comment by wmorgue** [comment]
Hi @eirisdg 
You steel need help with this issue?

**Comment by eirisdg** [comment]
No, thanks
