### ISSUE TITLE
Template 3.4 upd 3.11

### ISSUE THREAD

**Issue by vladislavotinov** [itmicus/zabbix#45]
Не загружается совсем обновленный 3.4 шаблон.
Старый 3.4 не отправляет запросы или не принимает. Постоянно метрика выдает нет данных от сайта,к какому бы я не обращался.
Все по гайду - создание хоста -> макросы -> нету хепи енда.

"Некорректное выражение триггера. Узел сети "Template - SSL metrics" не существует или у вас нет прав доступа к этому узлу сети. "

**Comment by vladislavotinov** [comment]
Template Web Site

**Comment by skazochnik97** [comment]
38fe3997030aa4dca6b6ffef8ef8f4975fa47b05
Починил баг с импортом шаблона.
Для версии zabbix server 3.4 шаблон назвал явно: Template_Website_metrics_34.xml
Обновил readme по установке пакетов python (вызов pip install -r requirements.txt).

Прошу проверить помогло ли.

**Comment by vladislavotinov** [comment]
Все импортируется. Но работа скрипта еще не уверенная
