### ISSUE TITLE
No data.

### ISSUE THREAD

**Issue by vladislavotinov** [itmicus/zabbix#46]
Web site "https://google.com" Nodata
{check_two:website_metrics.test.code.nodata(10m)}=1

Так же не решенный вопрос. Все что мог обновил

**Comment by vladislavotinov** [comment]
Template Web Site

**Comment by vladislavotinov** [comment]
![google](https://user-images.githubusercontent.com/26053644/69067074-20e56f00-0a2b-11ea-93df-ebe0a8bb9029.PNG)
Вот и что с этим поделать? Все по гайду.
Вот макросы - 
![google2](https://user-images.githubusercontent.com/26053644/69067250-6e61dc00-0a2b-11ea-92ae-e1bcb94a51ba.PNG)

**Comment by skazochnik97** [comment]
{$WEBSITE_METRICS_URL} должен содержать полный URL включая протокол и порт (если он нестандартный и отличается от 443). В указанном примере: {$WEBSITE_METRICS_URL} = https://google.com

{$WEBSITE_METRICS_TIMEOUT} и {$WEBSITE_METRICS_TIMEOUT_RECOVERY} указывает время в секундах ожидания. Такие большие числа указывать нерационально, так как сайты должны укладываться в разумное время ответа (скажем, 500мс), вдобавок время выполнения скрипта в системе Zabbix ограничено лимитом времени установленном в параметре Timeout и не может превышать 30 секунд. Предлагается значения установить {$WEBSITE_METRICS_TIMEOUT} в 5 и {$WEBSITE_METRICS_TIMEOUT_RECOVERY} в 3.

**Comment by vladislavotinov** [comment]
Учел Ваш ответ, но не помогло.
Итемы хоста

Item preprocessing step #1 failed: cannot extract value from json by path "$.test_time": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: 1: /usr/local/share/zabbix/externalscripts/website_metrics.py: not found'

Правила обнаружения (Discovery rules) 

Value should be a JSON object.

Проблемы - 
Так же и осталось - нет данных.

**Comment by skazochnik97** [comment]
Ключевое замечание, что не обнаружен скрипт по пути: /usr/local/share/zabbix/externalscripts/website_metrics.py

Путь до скриптов внешних проверок описывается в конфигурационных файлах zabbix_server.conf (для Сервера) или zabbix_proxy.conf (для Прокси) параметром ExternalScripts=. Вероятно сейчас там указан путь /usr/local/share/zabbix/externalscripts/ (путь по умолчанию, если не задан другой https://www.zabbix.com/documentation/3.2/manual/appendix/config/zabbix_server), и нужного скрипта проекта там нет.

Необходимо скрипты website_metrics.py, website_settings.py подложить в /usr/local/share/zabbix/externalscripts/ и предоставить права на выполнение.

**Comment by vladislavotinov** [comment]
Спасибо большое за поддержку. Но таки все по прежнему - 
![4](https://user-images.githubusercontent.com/26053644/69333288-16acb600-0c61-11ea-8f1d-60a446c92a76.PNG)

**Comment by wmorgue** [comment]
Привет @vladislavotinov 
Проблема актуальна на данный момент?

**Comment by vladislavotinov** [comment]
Привет @wmorgue 
Не актуальна. Скрипт работает прекрасно уже на протяжении года.
