### ISSUE TITLE
Cannot import template on zabbix 3.4 - tag "evaltype" is missing

### ISSUE THREAD

**Issue by alanwds** [itmicus/zabbix#5]
Hi,

I just try import the template to zabbix 3.4 and got erros:

`Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/filter": the tag "evaltype" is missing.`

Regards,

**Comment by skazochnik97** [comment]
fix at  #7cde195648efb8f3712d2a348692caf72e928f1d
