### ISSUE TITLE
Can not import the xml file 

### ISSUE THREAD

**Issue by yule-sun** [itmicus/zabbix#63]
When i import the xml file, i got this error.
413 Request Entity Too Large

**Comment by wmorgue** [comment]
Hi @yule-sun 

What `xml` file are you talking about? Please give more details

**Comment by skazochnik97** [comment]
@yule-sun try to increase client_max_body_size of nginx to high value;

https://medium.com/@svsh227/error-413-request-entity-too-large-in-nginx-with-client-max-body-size-changes-in-nginx-6aacd525fe11
