### ISSUE TITLE
Проблема с обнаружением SSL

### ISSUE THREAD

**Issue by kostyun** [itmicus/zabbix#68]
Добрый день!

Имеется множество сайтов, с которыми все хорошо
Но есть один на котором есть проблема с дектированием SSL сертификата
![изображение](https://user-images.githubusercontent.com/83953865/121774805-acce6700-cb8c-11eb-8ac1-840b637206fa.png)

![изображение](https://user-images.githubusercontent.com/83953865/121774819-d091ad00-cb8c-11eb-8055-1feefea4daf5.png)

![изображение](https://user-images.githubusercontent.com/83953865/121774856-08005980-cb8d-11eb-8c44-97baea431d6b.png)

Не пониманию почему. Подскажите в чем может быть проблема?

**Comment by skazochnik97** [comment]
@kostyun Доброго дня. Запретили http-редирерт при определении атрибутов SSL. Прошу обновить скрипт website_metrics.py по пути externalscripts Вашей установки Zabbix.
