### ISSUE TITLE
Import failed Template Zabbix 3.4.10

### ISSUE THREAD

**Issue by rafaelnikodem** [itmicus/zabbix#7]
Import failed
Details
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('Physical Disk \"{#PHYSICAL_DISK}\" Avg. Disk Read/sec','7','','','15s','1w','365d','0','0','','','','0','0','','0','','','','0','','','','','','perf_counter[\"\\PhysicalDisk({#PHYSICAL_DISK})\\Avg. Disk sec/Read\"]\r\n\r\nDisplays the average time the disk transfers took to complete, in seconds. Although the scale is seconds, the counter has millisecond precision, meaning a value of 0.004 indicates the average time for disk transfers to complete was 4 milliseconds. \r\nThis is the counter in Perfmon used to measure IO latency. \r\nI wrote a blog specifically about measuring latency with Perfmon. For details got to “Measuring Disk Latency with Windows Performance Monitor”. \r\n\r\nhttp://blogs.technet.com/b/askcore/archive/2012/02/07/measuring-disk-latency-with-windows-performance-monitor-perfmon.aspx\r\n\r\nСчетчик производительности Avg. Disk sec/Read указывает среднее время считывания данных с диска в секундах. Среднее значение счетчика производительности Avg. Disk sec/Read не должно превышать 10 миллисекунд. Максимальное значение счетчика производительности Avg. Disk sec/Read не должно превышать 50 миллисекунд.','0','','','wmi.get[root\\cimv2,select AvgDisksecPerRead from Win32_PerfFormattedData_PerfDisk_PhysicalDisk where Name=\'{#PHYSICAL_DISK}\']','','10367',NULL,'2','37474')] [Incorrect string value: '\xD0\xA1\xD1\x87\xD0\xB5...' for column 'description' at row 1]
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('Physical Disk \"{#PHYSICAL_DISK}\" Avg. Disk Read/sec','7','','','15s','1w','365d','0','0','','','','0','0','','0','','','','0','','','','','','perf_counter[\"\\PhysicalDisk({#PHYSICAL_DISK})\\Avg. Disk sec/Read\"]\r\n\r\nDisplays the average time the disk transfers took to complete, in seconds. Although the scale is seconds, the counter has millisecond precision, meaning a value of 0.004 indicates the average time for disk transfers to complete was 4 milliseconds. \r\nThis is the counter in Perfmon used to measure IO latency. \r\nI wrote a blog specifically about measuring latency with Perfmon. For details got to “Measuring Disk Latency with Windows Performance Monitor”. \r\n\r\nhttp://blogs.technet.com/b/askcore/archive/2012/02/07/measuring-disk-latency-with-windows-performance-monitor-perfmon.aspx\r\n\r\nСчетчик производительности Avg. Disk sec/Read указывает среднее время считывания данных с диска в секундах. Среднее значение счетчика производительности Avg. Disk sec/Read не должно превышать 10 миллисекунд. Максимальное значение счетчика производительности Avg. Disk sec/Read не должно превышать 50 миллисекунд.','0','','','wmi.get[root\\cimv2,select AvgDisksecPerRead from Win32_PerfFormattedData_PerfDisk_PhysicalDisk where Name=\'{#PHYSICAL_DISK}\']','','10367',NULL,'2','37474')".

**Comment by itmicus** [comment]
Hm, I think it is issue with unicode and russain lang in item's comment.
I want to upgrade this template in 2-3 days and remove russian comments from items.

**Comment by itmicus** [comment]
please check now
#9

**Comment by rafaelnikodem** [comment]
Thank you very much, it worked perfectly to import the template
