### ISSUE TITLE
скрипт возвращает we have

### ISSUE THREAD

**Issue by Kynepok** [itmicus/zabbix#77]
Добрый день! Сделал всё по шаблону и примеру, однако при получении информации о домене, скрипт возвращает дополнительную переменную "we have *", где * - домен сайта. 
![Аннотация 2023-03-15 105425](https://user-images.githubusercontent.com/88827908/225230810-dc6a587d-533a-421a-9aef-5f289c6e2cb8.png)

Zabbix естественно не может обработать это, и выдаёт ошибку:  
![Аннотация 2023-03-15 105942](https://user-images.githubusercontent.com/88827908/225231666-2e7fc99c-3dbf-4cd2-9124-521962ab7eaf.png)

Как побороть? Заранее благодарю.

**Comment by skazochnik97** [comment]
Кто-то забыл выключить отладку в последнее версии библиотеки whois.
Чтобы быстро исправить, прошу откатить библиотеку командой:

`pip install whois==0.9`

**Comment by Kynepok** [comment]
Спасибо.
