### ISSUE TITLE
website_metrics passive proxy

### ISSUE THREAD

**Issue by Kynepok** [itmicus/zabbix#78]
Добрый день. запускаю Ваш скрипт непосредственно с сервера, либо с активного прокси - всё работает. запускаю с пассивного прокси - обнаружение ssl отрабатывает, а testssl - нет, возвращает пустоту 
![Аннотация 2023-03-16 115105](https://user-images.githubusercontent.com/88827908/225550066-82548ed2-014a-4e6d-bc55-8e27816b1f71.png)

Так и должно быть?

**Comment by skazochnik97** [comment]
Скрипт падает молча, это известный баг.

Нужно сравнить версии библиотек на работающем сервере с неработающим, предполагаю есть расхождения. Делается это командой:
`pip3 freeze`

Целевые версии указаны в файле requirements.txt. Чтобы по нему привести версии к одном виду есть команда:
`pip3 install -r requirements.txt`

**Comment by Kynepok** [comment]
> 
инстал необходимых пакетов как раз и проводился из файла requirements.txt, полное следование инструкции.

**Comment by skazochnik97** [comment]
@Kynepok чтобы понять конфликты, прошу показать выхлоп команды:
`pip3 freeze`

**Comment by Kynepok** [comment]
@skazochnik97  первый файлик выхлоп пипа с рабочего сервера
[requirements.txt](https://github.com/itmicus/zabbix/files/11046984/requirements.txt)
второй файлик - с пассивной прокси
[requirements_no_ssl.txt](https://github.com/itmicus/zabbix/files/11046998/requirements_no_ssl.txt)

Заранее благодарю за помощь!

**Comment by skazochnik97** [comment]
@Kynepok лечение такое:
pip3 install requests>=2.26.0

**Comment by Kynepok** [comment]
@skazochnik97 огромное спасибо за уделённое время. апгрейд действительно помог, тестссл выдавать пустоту перестал. спасибо за Вашу работу!
